name: Build and Deploy Site

on:
  push:
    branches:
      - master  # Trigger on the master branch of your main repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true  # Fetch submodules

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    - name: Install dependencies
      run: |
        cd blog
        bundle install

    - name: Build Blog Site
      run: |
        cd blog
        bundle exec jekyll build
        mkdir -p ../_site/blog  # Ensure the destination directory exists
        mv _site/* ../_site/blog/  # Move the built blog site to the main _site/blog directory

    - name: Copy Static Site Files
      run: |
        cp index.html _site/
        cp style.css _site/
        cp assets _site/


    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        publish_branch: gh-pages  # Ensure this is set to gh-pages
